# Generated by Django 5.0.1 on 2024-02-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todoapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="date",
            field=models.DateField(default="2000-04-24"),
            preserve_default=False,
        ),
    ]
